artifacts: artifacts

data_ingestion:
 root_dir : artifacts/data_ingestion
 data_url : https://github.com/senthil100695/Branching_dataset/raw/main/data.zip
 local_data_file : artifacts/data_ingestion/data.zip
 unzip_dir : artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  data_path : artifacts/data_ingestion/article.csv
  status : artifacts/data_validation/status.txt

prepare_base_model:
  
 
