artifacts_root: artifacts

data_ingestion:
 root_dir : artifacts/data_ingestion
 source_URL : https://github.com/senthil100695/Branching_dataset/raw/main/article.zip
 local_data_file : artifacts/data_ingestion/data.zip
 unzip_dir : artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["article.csv",'data.zip']


data_preprocess:
  root_dir: artifacts/data_preprocess
  data_path: artifacts/data_ingestion/article.csv
  indepent_feature: ['Heading', 'Article.Description', 'Full_Article']
  drop_feature: ['Article.Banner.Image','Outlets','Id','Tonality']
  target_feature: 'Article_Type'
  preprocess_data_path: artifacts/data_preprocess/
  

base_model:
  root_dir: artifacts/base_model
  model_name: 'all-MiniLM-L12-v2'
  base_model_path : artifacts/base_model/
  


model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv
  
 
